In [1]:
print ("Hello, world!\n")

Hello, world!



In [2]:
import os
cwd = os.getcwd()
print(cwd)

/home/sqchen


In [2]:
import sys

print("sys.prefix =", sys.prefix )
print("sys.base_prefix =", sys.base_prefix )

sys.prefix = /usr
sys.base_prefix = /usr


In [ ]:
import torch

In [2]:
x = torch.arange(12, dtype=torch.float32)
x


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
x.numel()

12

In [4]:
x.shape

torch.Size([12])

In [5]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
from d2l import torch as d2l